[graph]
all-features = false

[advisories]
ignore = []
unmaintained = "all"
yanked = "deny"

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Unicode-3.0",
]
confidence-threshold = 0.8
unused-allowed-license = "warn"

[licenses.private]
ignore = false

[bans]
multiple-versions = "deny"
wildcards = "deny"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
